# Numpy

Numpy fornece um grande conjunto de funções e operações de bibliotecas que ajudam os programadores a executar facilmente calculos numéricos

<img src="41586_2020_2649_Fig1_HTML.png"></img>

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.4


In [6]:
#criar uma matriz 

Array = np.array([10, 20, 30, 40])
print(Array)

type(Array)

[10 20 30 40]


numpy.ndarray

In [8]:
Duas = np.array([[10, 9, 8, 7, 6], [5, 4, 3, 2, 1]])

print(Duas)

[[10  9  8  7  6]
 [ 5  4  3  2  1]]


In [10]:
tres = np.array([[10, 9, 8, 7, 6], [5, 4, 3, 2, 1], [5, 4, 3, 2, 1,]])

display(tres)

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1],
       [ 5,  4,  3,  2,  1]])

In [20]:
# Experimento de processamento

estressando_np = np.arange(1000000)
estressando_np_02 = np.arange(100000000)

len(estressando_np)
len(estressando_np_02)

100000000

In [21]:
# 1 Teste

%time for Loop in estressando_np: pass
%time for Loop in estressando_np_02: pass


CPU times: total: 78.1 ms
Wall time: 134 ms
CPU times: total: 3.16 s
Wall time: 8.9 s


In [23]:
#Acessar os Arrays

# 1 posicao

Array[0]
Array[-1]

40

In [25]:
Array[0] + Array[2]

# Posso fazer qualquer tipo de operacao com os Arrays

40

In [26]:
Duas.shape

(2, 5)

In [29]:
for Loop in Array:
    print(Loop)

10
20
30
40


In [30]:
import pandas as pd

In [31]:
pd.DataFrame(Array)

0
0  10
1  20
2  30
3  40